"""add status to textentry

Revision ID: 1c9f4b2d3a4b
Revises: a7b503bbec1f
Create Date: 2025-09-28 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c9f4b2d3a4b'
down_revision: Union[str, Sequence[str], None] = 'a7b503bbec1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textentry', sa.Column('status', sa.String(), nullable=False, server_default='Processando'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('textentry', 'status')
    # ### end Alembic commands ###
