"""add file metadata to textentry

Revision ID: a7b503bbec1f
Revises: 
Create Date: 2025-09-27 17:55:04.582961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7b503bbec1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textentry', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('textentry', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('textentry', sa.Column('file_content_type', sa.String(), nullable=True))
    op.add_column('textentry', sa.Column('file_size', sa.Integer(), nullable=True))
    op.alter_column('textentry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('textentry', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('textentry', 'file_size')
    op.drop_column('textentry', 'file_content_type')
    op.drop_column('textentry', 'file_path')
    op.drop_column('textentry', 'file_name')
    # ### end Alembic commands ###
